# Generated by Django 5.0.6 on 2024-06-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
